# Generated by Django 3.1.7 on 2021-03-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='question',
            field=models.CharField(max_length=100),
        ),
    ]
